### ISSUE TITLE
odgi bin does not seem to use odgi lib even when compiled non statically

### ISSUE THREAD

**Issue by JervenBolleman** [pangenome/odgi#108]
In the quest to make smaller docker images I realized that the odgi binary does not depend on the compiled library.

Using the docker branch docker commit e9c6a595dcbeb75975642054cef0b33d1dc2135a
```
docker build -t test/odgi
docker run -it -entrypoint=bash test/odgi 
odgi test
rm /opt/odgi/lib/libodgi.so
odgi test
```
Both test cases pass.
the docker builds with
```
-DBUILD_STATIC=0
```
Which leads to an assumption that the odgi library would use the shared libs. But it doesn't seem to do so in practice.

**Comment by subwaystation** [comment]
@JervenBolleman Is this still something you are worried about?
Thanks to the Bioconda package, we now also have a docker image of `odgi`: `docker pull quay.io/biocontainers/odgi:<tag>`. Where `<tag>` could be e.g. `latest`.

**Comment by JervenBolleman** [comment]
@subwaystation no I am no longer worried about how this affects spodgi. But it is still annoying ;)

**Comment by subwaystation** [comment]
So the problem is that, although you compiled odgi dynamically, it still runs in a static setting, because when you remove the actual dynamic library, it still executes. Hmm. This goes totally over my knowledge with CMake. 
I will leave this open, maybe someone else knows more.

**Comment by JervenBolleman** [comment]
@subwaystation no the problem is that even when dynamically compiled the odgi binary does not use the library file. So the odgi binary is still huge, and we got a huge lib file.

Also I can't use the biocontainers/odgi as the image is very limited I can't use it as a base docker image.

In any case it also suffers from overbloat due to having 2 libodgi and a huge odgi binary.
sh-5.0# ls -lh /usr/local/lib/libodgi.a
-rw-rw-r--    1 root     root      447.9M Jun 17 13:14 /usr/local/lib/libodgi.a
sh-5.0# ls -lh /usr/local/lib/libodgi.so
-rwxrwxr-x    1 root     root      246.6M Jun 17 13:15 /usr/local/lib/libodgi.so
sh-5.0# ls -lh /usr/local/bin/odgi
-rwxrwxr-x    1 root     root      248.4M Jun 17 13:15 /usr/local/bin/odgi

**Comment by subwaystation** [comment]
@pjotrp Maybe you understand this? Since you are also working on https://github.com/pangenome/odgi/pull/372.

**Comment by pjotrp** [comment]
The shared lib you need for the FFI bindings. The files are large because cmake compiles with -g AND the binary pulls in some static libs. Optimizing for size should be fairly easy. In preparation for FFI I have been looking at runtime performance and I'll push a patch in the coming days. We can look at size after.

**Comment by pjotrp** [comment]
Hi @JervenBolleman. I just pushed https://github.com/pangenome/odgi/commit/c1c908e2de1b30bef3e668a3d6e58d56095c8ebb which should lead to smaller builds. The default build for odgi binary is around 7.5Mb and can be even smaller (see header of CMakeLists.txt and INSTALL.md). We always link against the static lib because the shared lib performs 10% slower. For making a Docker image just remove libodgi.a and libodgi.so.
