### ISSUE TITLE
Depth question

### ISSUE THREAD

**Issue by jonahcullen** [pangenome/odgi#545]
Hello, thank you for providing this excellent tool and very detailed tutorials. I am just learning this stuff so I carefully went through each of the readthedocs tutorials. I had a quick question about `odgi depth` from [detecting complex regions](https://odgi.readthedocs.io/en/latest/rst/tutorials/detect_complex_regions.html#). The description indicates there were 88 haploid, phased assemblies plus two reference genomes. I was wondering how can depths greater than 90 can be achieved? I'm quite sure I'm just not wrapping my head around the graph structure that allows a depth of 90k. For example, I created a simple graph from 3 assemblies and a reference on one chromosome and found the greatest depth to be 4.99.

Thank you for your time!

**Comment by ekg** [comment]
This happens due to looping motifs in the graph, which represent VNTR type loci. The looping results from an evolutionary process of indels and gene conversion. Intuitively, it can be ambiguous how to place indels across many pairs of comparisons between sequences. This quickly can induce a "collapse" of repetitive sequences in the graph. Graphs built this way have one region representing the ancestral sequence that expanded into the repeat, and each haplotype loops through the region a number of times corresponding to the copy number.

**Comment by jonahcullen** [comment]
Ah okay, thank you very much for the clarification!
