### ISSUE TITLE
odgi build cannot process HPRC minigraph gfa

### ISSUE THREAD

**Issue by adadiehl** [pangenome/odgi#546]
Source data: https://zenodo.org/records/6983934

Command 1: `odgi build -g GRCh38-90c.r518.gfa.gz -o hprc-v1.0-minigraph-grch38.og`
Output:
![image](https://github.com/pangenome/odgi/assets/11062473/dadf300f-5808-4982-a782-70bebbf5218d)

Command 2: `odgi build -g <(zcat GRCh38-90c.r518.gfa.gz) -o hprc-v1.0-minigraph-grch38.og`
Output: 
![image](https://github.com/pangenome/odgi/assets/11062473/c900e1d9-7ab1-4046-8022-d50f2f3eb723)

Output file is produced within seconds and appears to have no content.

Command 3: `gunzip GRCh38-90c.r518.gfa.gz; odgi build -g GRCh38-90c.r518.gfa -o hprc-v1.0-minigraph-grch38.og`
Output: 
![image](https://github.com/pangenome/odgi/assets/11062473/f8f12015-a980-41c3-b03f-1e11463d5cd1)

**Comment by AndreaGuarracino** [comment]
The first 2 commands can't work. `odgi` requires an uncompressed GFA file and it has to be on disk.

The 3rd does not work because `odgi` supports a subset of the GFAv1.0 format. It needs integers as segment (node) IDs. If you hack the GFA files by changing segment IDs, you should be able to get an odgi graphs.

**Comment by subwaystation** [comment]
If you don't have `P` lines that encode paths in the GFA that you might have to use `vg convert` to go from the minigraph GFA to GFAv1.0. Thanks.
